connection:
  host: "127.0.0.1:3306"
  username: ""
  password: ""
  database: "quill"

server_name: "A Minecraft Server"
player_tag_format: "[%tag%] %player%"

welcome_msg:
  first_time:
    fadein: 15
    stay: 200
    fadeout: 15
    message: "ようこそ %server_name% へ!"
    sub_message: "はじめまして, %player%!"
    chat_message: "ようこそ %server_name% へ!"
  chat_message: "おかえりなさい%player%！"

notificatio_death_location:
    enable: true
    command_message: "%player%の最終死亡座標: (%world%: %x%, %y%, %z%)"
