name: QUILL
version: '${project.version}'
main: com.mai_llj.plugin.quill
authors: [ mai_llj ]
description: Helping to ensure smooth server operations.

commands:
  placedinfo:
    description: 対象ブロックの設置者や設置時刻を取得します。
    usage: /placedinfo
    aliases: [ plif ]
    permission: quill.putblockinfo
    permission-message: 権限が不足しています。

  deadlocation:
    description: 最終に死亡した地点のディメンションと座標を取得します。
    usage: /deadlocation
    aliases: [ dloc ]
    permission: quill.deathlocation
    permission-message: 権限が不足しています。

  tag:
    description: プレイヤーに任意のタグを設定します。
    usage: /tag <プレイヤー名> <称号>
    aliases: [ tg ]
    permission: quill.tag
    permission-message: 権限が不足しています。