name: QUILL
version: '${project.version}'
main: com.mai_llj.plugin.quill
authors: [ mai_llj ]
description: Helping to ensure smooth server operations.

commands:
  placedinfo:
    description: 対象ブロックの設置者や設置時刻を取得します。
    usage: /placedinfo
    aliases: [ plif ]
    permission: quill.putblockinfo
    permission-message: 権限が不足しています。